[env:d1_mini]
platform = espressif8266
board = d1_mini
framework = arduino
monitor_speed = 115200
lib_deps =
  olikraus/U8g2
  adafruit/Adafruit AHTX0
  bblanchon/ArduinoJson
  knolleary/PubSubClient
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
  olikraus/U8g2
  adafruit/Adafruit AHTX0
  bblanchon/ArduinoJson
  knolleary/PubSubClient